[package]
name = "embrio-async"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[dependencies]
embrio-async-dehygiene = { path = "dehygiene" }
futures-core-preview = { version = "0.3.0-alpha.12", default-features = false }
futures-sink-preview = { version = "0.3.0-alpha.12", default-features = false }
pin-utils = "0.1.0-alpha.4"

[dev-dependencies]
futures-preview = "0.3.0-alpha.12"
